<a href="https://colab.research.google.com/github/giovanni-lucarelli/basket/blob/main/DataWrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd

url = "https://raw.githubusercontent.com/giovanni-lucarelli/basket/main/games.csv"
df = pd.read_csv(url)

In [3]:
print(df.head())

  GAME_DATE_EST   GAME_ID GAME_STATUS_TEXT  HOME_TEAM_ID  VISITOR_TEAM_ID  \
0    2022-12-22  22200477            Final    1610612740       1610612759
1    2022-12-22  22200478            Final    1610612762       1610612764
2    2022-12-21  22200466            Final    1610612739       1610612749
3    2022-12-21  22200467            Final    1610612755       1610612765
4    2022-12-21  22200468            Final    1610612737       1610612741

   SEASON  TEAM_ID_home  PTS_home  FG_PCT_home  FT_PCT_home  ...  AST_home  \
0    2022    1610612740     126.0        0.484        0.926  ...      25.0
1    2022    1610612762     120.0        0.488        0.952  ...      16.0
2    2022    1610612739     114.0        0.482        0.786  ...      22.0
3    2022    1610612755     113.0        0.441        0.909  ...      27.0
4    2022    1610612737     108.0        0.429        1.000  ...      22.0

   REB_home  TEAM_ID_away  PTS_away  FG_PCT_away  FT_PCT_away  FG3_PCT_away  \
0      46.0    1610612759     117.0        0.478        0.815         0.321
1      40.0    1610612764     112.0        0.561        0.765         0.333
2      37.0    1610612749     106.0        0.470        0.682         0.433
3      49.0    1610612765      93.0        0.392        0.735         0.261
4      47.0    1610612741     110.0        0.500        0.773         0.292

   AST_away  REB_away  HOME_TEAM_WINS
0      23.0      44.0               1
1      20.0      37.0               1
2      20.0      46.0               1
3      15.0      46.0               1
4      20.0      47.0               0

[5 rows x 21 columns]

In [10]:
df.dropna(inplace=True)

In [12]:
import pandas as pd
import random

# Pick a random HOME_TEAM_ID
random_team_id = random.choice(df['HOME_TEAM_ID'].unique())
print(f"Selected team ID: {random_team_id}")

# Filter games where the team is either home or visitor
team_games = df[
    (df['HOME_TEAM_ID'] == random_team_id) | (df['VISITOR_TEAM_ID'] == random_team_id)
]

# Order by game date
team_games_sorted = team_games.sort_values(by='GAME_DATE_EST')

# Get the first six games
first_six_games = team_games_sorted.head(6)

# Display the dataframe
first_six_games

Selected team ID: 1610612743

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
19168,2003-10-29,20300011,Final,1610612743,1610612759,2003,1610612743,80.0,0.292,0.690,...,17.0,66.0,1610612759,72.0,0.268,0.783,0.154,14.0,60.0,1
19158,2003-10-30,20300017,Final,1610612745,1610612743,2003,1610612745,102.0,0.487,0.750,...,21.0,44.0,1610612743,85.0,0.356,0.806,0.308,10.0,38.0,1
19145,2003-11-01,20300036,Final,1610612743,1610612758,2003,1610612743,109.0,0.488,0.821,...,25.0,49.0,1610612758,88.0,0.363,0.692,0.267,24.0,41.0,1
19125,2003-11-04,20300048,Final,1610612754,1610612743,2003,1610612754,71.0,0.355,0.739,...,21.0,49.0,1610612743,60.0,0.291,0.667,0.222,12.0,49.0,1
19118,2003-11-05,20300057,Final,1610612739,1610612743,2003,1610612739,89.0,0.379,0.677,...,19.0,56.0,1610612743,93.0,0.432,0.556,0.368,17.0,42.0,0
19107,2003-11-07,20300073,Final,1610612743,1610612746,2003,1610612743,102.0,0.384,0.708,...,21.0,51.0,1610612746,104.0,0.453,0.765,0.385,24.0,52.0,0